dist: focal

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t simplicissimus/nodejs_app .
      - docker images
      - docker tag simplicissimus/nodejs_app:latest simplicissimus/nodejs_app:travis
      - docker push simplicissimus/nodejs_app:travis
    - stage: deploy
      script:
      - openssl aes-256-cbc -pass "pass:$secret" -in ./my_key.enc -out ./my_key -d -a
      - eval "$(ssh-agent -s)"
      - chmod 600 my_key
      - ssh-add my_key
      - ssh -o "StrictHostKeyChecking=no" ubuntu@ec2-3-83-11-158.compute-1.amazonaws.com 'bash ./deploy.sh'
