dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t simplicissimus/nodejs_app .
      - docker images
      - docker tag simplicissimus/nodejs_app:latest simplicissimus/nodejs_app:travis
      - docker push simplicissimus/nodejs_app:travis
    - stage: test
      script: docker run --rm simplicissimus/nodejs_app:travis cat package.json
    - script: docker run --rm simplicissimus/nodejs_app:travis cat package.json
    
