dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t simplicissimus/nodejs_app .
      - docker images
      - docker tag simplicissimus/nodejs_app:latest simplicissimus/nodejs_app:travis
      - docker push simplicissimus/nodejs_app:travis
    - stage: deploy
      script: 
      - echo "$lod" > lod.pem 
      - ssh -i "lod.pem" -o "StrictHostKeyChecking no" ubuntu@ec2-3-83-11-158.compute-1.amazonaws.com exit
      - echo $?
